github.com:
    user: BlackMageZeraf
    git_protocol: https
    users:
        BlackMageZeraf:
            oauth_token: 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
    oauth_token: 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
